config/routes.rb
Rails.application.routes.draw do
  get '/weather', to: 'weather#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
require 'httparty'

class WeatherController < ApplicationController
  def index
    populate_weather_forecast_details
  rescue => e
    @error_message = e.message
  end

  private

  def populate_weather_forecast_details
    return @weather_forecast_details if defined?(@weather_forecast_details)
    return @weather_forecast_details = {} unless address.present?
    if (@weather_forecast_details = Rails.cache.read(params[:zip_code]))
      @from_cache = true
      return @weather_forecast_details
    end

    parsed_response = query_open_weather_api

    @weather_forecast_details = {
      current: "#{parsed_response["current"]["temp"]}F",
      forecasts: parsed_response["daily"].map do |forecast|
        {
          date: Time.at(forecast["dt"]).strftime('%m/%d'),
          high: "#{forecast["temp"]["max"]}F",
          low: "#{forecast["temp"]["min"]}F"
        }
      end
    }

    Rails.cache.write(params[:zip_code], @weather_forecast_details, expires_in: 30.minutes)
  end

  def query_open_weather_api
    weather_forecast_url = "https://api.openweathermap.org/data/3.0/onecall"

    query = {
      lat: address_coordinates[:latitude],
      lon: address_coordinates[:longitude],
      exclude: "minutely,hourly,alerts",
      units: "imperial",
      appid: "a53cfe4549bc0249d5df478de84f0f10"
    }

    response = HTTParty.get(weather_forecast_url, query:)

    raise response.parsed_response["message"] if response.code != 200

    response.parsed_response
  end

  def address
    @address ||= [
      params[:address_line_1],
      params[:city],
      "#{params[:state]} #{params[:zip_code]}",
      params[:country]
    ].compact.join(', ').strip
  end

  def address_coordinates
    return @address_coordinates if defined?(@address_coordinates)

    results = Geocoder.search(address)

    raise "The given address does not exist." unless results.first.present?

    @address_coordinates = {
      latitude: results.first.coordinates[0],
      longitude: results.first.coordinates[1]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppleDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/index.html.erb
<h1>Weather Forecast</h1>
<p>Enter your address:</p>
<%= form_tag(weather_path, method: "get") do %>
  <div>
    <%= label_tag(:address_line_1, "Address Line 1") %>
    <%= text_field_tag(:address_line_1, '', required: true) %>
  </div>
  <div>
    <%= label_tag(:city, "City") %>
    <%= text_field_tag(:city, '', required: true) %>
  </div>
  <div>
    <%= label_tag(:state, "State") %>
    <%= text_field_tag(:state, '', required: true) %>
  </div>
  <div>
    <%= label_tag(:zip_code, "Zip Code") %>
    <%= text_field_tag(:zip_code, '', required: true) %>
  </div>
  <div>
    <%= label_tag(:country, "Country") %>
    <%= text_field_tag(:country, '', required: true) %>
  </div>
  <div>
    <%= submit_tag("Search") %>
  </div>
<% end %>

<% if @weather_forecast_details.present? %>
  <div test_id="weather_forecast_details">
    <% if @from_cache %>
      <p>This data was retrieved from the cache.</p>
    <% end %>
    <p>Current: <%= @weather_forecast_details[:current] %></p>
    <% @weather_forecast_details[:forecasts].each do |forecast| %>
      <p><%= forecast[:date] %> High: <%= forecast[:high] %> Low: <%= forecast[:low] %></p>
    <% end %>
  </div>
<% end %>

<% if @error_message.present? %>
  <div test_id="error_message">
    <p>There was an error retrieving the weather forecast details: <%= @error_message %></p>
  </div>
<% end %>